### ISSUE TITLE
Note on Brave's handling on ABA embeds

### ISSUE THREAD

**Issue by pes10k** [DCtheTall/standardizing-cross-site-cookie-semantics#3]
thank you for writing this up and circulating it!

In case it might be of interest to the authors, I wanted to note that Brave's handling of 3p cookies in general, and ABA embeds is different than the other browsers mentioned here:

As background, unique from other browsers, Brave:

 i. does not enable (or plan to enable) Storage Access API, and
 ii. partitions storage in 3p frames under the eTLD+1 of the top frame, and clears those partitions shortly (~30 sec currently) after there are no more top-level frames with the same eTLD+1 open
 
We currently allow ABA embeds full r/w access to the same storage area as the top level frame, which makes Brave's handling of ABA frames closest to Safari's (though w/o the SAA support). We're not fixed or committed to this though, and would probably be fine aligning with others on this if other browsers do 

We're also considering (for it becomes necessary for compat reasons in the future) possibly enabling a modified Storage Access API implementation that always resolves 'accepted', but which results in the same access patterns as the above (i.e., even after a SSA resolves accepted in a 3p frame, we would still clear state for that frame when there are no longer any top level frames with the current eTLD+1).

Not sure anything turns the above, no worries to close this issue immediately if its not useful, but mostly wanted to note that there are other handlings of 3p state / ABA frames in the wild

**Comment by krgovind** [comment]
Thanks for the note, @pes10k. We are focusing on ABA-style embeds in this document; so I am updating the corresponding section with Brave's handling of that case in #4. Happy to note that you may be fine aligning with other browsers, including possibly requiring the invocation of SAA.
